apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "klaytn-safe-txn.name" . }}-web"
  labels:
    {{- include "klaytn-safe-txn.labels" . | nindent 4 }}
    component: "{{- include "klaytn-safe-txn.name" . }}-web"
spec:
  selector:
    matchLabels:
      {{- include "klaytn-safe-txn.selectorLabels" . | nindent 6 }}
      component: "{{- include "klaytn-safe-txn.name" . }}-web"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "klaytn-safe-txn.selectorLabels" . | nindent 8 }}
        component: "{{- include "klaytn-safe-txn.name" . }}-web"
    spec:
      serviceAccountName: {{ include "klaytn-safe-txn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: {{ .Values.web.nginx.repository }}:{{ .Values.web.nginx.tag }}
          imagePullPolicy: {{ .Values.web.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.servicePort }}
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: django-statics
              mountPath: /var/www
        - name: "web-services"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          command: ["/bin/bash"]
          args: ["/app/docker/web/run_web.sh"]
          env:
            {{- include "klaytn-safe-txn.web" . | indent 12 }}
          volumeMounts:
            - mountPath: /nginx
              name: django-statics
      volumes:
        - name: nginx-config
          configMap:
            name: "{{ include "klaytn-safe-txn.name" .}}-nginx-configmap"
        - name: django-statics
          emptyDir: {}
        
