apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "klaytn-safe-txn.name" . }}-indexer-worker"
  labels:
    {{- include "klaytn-safe-txn.labels" . | nindent 4 }}
    component: "{{ include "klaytn-safe-txn.name" . }}-indexer-worker"
spec:
  selector:
    matchLabels:
      {{- include "klaytn-safe-txn.selectorLabels" . | nindent 6 }}
      component: "{{ include "klaytn-safe-txn.name" . }}-indexer-worker"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "klaytn-safe-txn.selectorLabels" . | nindent 8 }}
        component: "{{ include "klaytn-safe-txn.name" . }}-indexer-worker"
    spec:
      serviceAccountName: {{ include "klaytn-safe-txn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "worker"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.indexerWorker.resources | nindent 12 }}
          command: ["/bin/bash"]
          args: ["/app/docker/web/celery/worker/run.sh"]
          env:
            {{- include "klaytn-safe-txn.indexerWorker" . | indent 12 }}
        
