apiVersion: v2
name: klaytn-safe
version: 1.0.0
dependencies:
  - name: klaytn-safe-txn
    alias: klaytn-safe-txn-baobab
    version: 1.0.0
    repository: "file://charts/klaytn-safe-txn"
    condition: klaytn-safe-txn-baobab.enabled
  - name: klaytn-safe-txn
    alias: klaytn-safe-txn-cypress
    version: 1.0.0
    repository: "file://charts/klaytn-safe-txn"
    condition: klaytn-safe-txn-cypress.enabled
  - name: klaytn-safe-config
    version: 1.0.0
    repository: "file://charts/klaytn-safe-config"
    condition: klaytn-safe-config.enabled
  - name: klaytn-safe-gateway
    version: 1.0.0
    repository: "file://charts/klaytn-safe-gateway"
    condition: klaytn-safe-gateway.enabled