{{- if .Values.klaytnSafeAdmin.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: klaytn-safe-admin
  labels:
    app.kubernetes.io/name: klaytn-safe-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "klaytn-safe-admin.chart" . }}
  {{- with .Values.klaytnSafeAdmin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.klaytnSafeAdmin.ingress.className }}
  ingressClassName: {{ .Values.klaytnSafeAdmin.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.klaytnSafeAdmin.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.klaytnSafeAdmin.ingress.paths }}
          - path: {{ .path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ default 80 .servicePort }}
          {{- end }}
{{- end }}