{{- range $externalSecret :=  .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $externalSecret.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $externalSecret.secretName }}
    creationPolicy: Owner
  data:
  {{- range $secret := $externalSecret.secrets }}
  - secretKey: {{ $secret.key }}
    remoteRef:
      key: {{ $externalSecret.secretManagerName }}
      property: {{ $secret.property }}
  {{- end }}
{{- end }}
