apiVersion: v1
kind: Service
metadata:
  name: {{ include "klaytn-safe-gateway.name" .}}-web
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ include "klaytn-safe-gateway.healthcheckPath" . }}
  labels:
    {{- include "klaytn-safe-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.servicePort }}
      targetPort: {{ .Values.web.servicePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "klaytn-safe-gateway.selectorLabels" . | nindent 4 }}
    component: "{{ include "klaytn-safe-gateway.name" . }}-web"
